Announcements/Controllers/AnnouncementController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Announcements.Helpers;
using Announcements.Helpers.Attributes;
using Announcements.Helpers.Html;
using Announcements.Models.DbContext;
using Announcements.Models.Mapping;
using Announcements.Models.ViewModels;


namespace Announcements.Controllers
{
    [Roles(Enums.Enums.Role.admin)]
    public class AnnouncementController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            var model = new AnnouncementViewModel();
            return PartialView("Partials/_Editor", model);
        }
        
        public ActionResult Edit(ActionFormBaseClass model)
        {
            if (model.FormActionValueGuid.HasValue)
            {
                try
                {
                    using (var db = new AnnouncementsContext())
                    {
                        var announcement = db.Announcements.FirstOrDefault(w => w.AnnouncementId == model.FormActionValueGuid);
                        if (announcement != null)
                        {
                            return PartialView("Partials/_Editor", announcement.ToModel());
                        }
                        else
                        {
                            ModelState.AddModelError("Error", "No Announcement");
                            return PartialView("Partials/_Editor", new AnnouncementViewModel());
                        }
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Error", ex.Message);
                }
            }

            ModelState.AddModelError("Error","No Announcement");
            return PartialView("Partials/_Editor", new AnnouncementViewModel());
        }

        public ActionResult Save(AnnouncementViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("Partials/_Editor", model);
            }

            try
            {
                using (var db = new AnnouncementsContext())
                {
                    var announcement = model.ToEntity();
                    if (model.AnnouncementId.HasValue)
                    {
                        db.Entry(announcement).State = EntityState.Modified;
                    }
                    else
                    {
                        announcement.AnnouncementId = Guid.NewGuid();
                        db.Announcements.Add(announcement);
                    }

                    db.SaveChanges();
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("UnknownError",ex.Message);
                return PartialView("Partials/_Editor", model);
            }
            GlobalMessages.AddSuccessMessage(Session, "Announcement has been saved.");
            return Json(new { success = true });
        }


        public ActionResult Delete(ActionFormBaseClass model)
        {
            if (model.FormActionValueGuid.HasValue)
            {
                try
                {
                    using (var db = new AnnouncementsContext())
                    {
                        var deleteAnnouncement =
                            db.Announcements.FirstOrDefault(w => w.AnnouncementId == model.FormActionValueGuid);
                        if (deleteAnnouncement != null)
                        {
                            deleteAnnouncement.IsActive = false;
                            db.Entry(deleteAnnouncement).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                    }
                }
                catch (Exception ex)
                {
                    GlobalMessages.AddErrorMessage(Session, ex.Message);
                }
            }

            GlobalMessages.AddSuccessMessage(Session, "Announcement has been removed.");
            return Json(new { success = true });
        }

    }
}

Announcements/Views/Shared/_Layout.cshtml
@using Announcements.Enums
@using Announcements.Helpers.Html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Test Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id='myModal' class='modal fade in'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div id='myModalContent' is-modal></div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated && User.IsInRole(Enums.Role.admin.ToString()))
                    {
                        <li>@Html.ActionLink("Announcements Editor", "Index", "Announcement")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.RenderMessages()
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Test Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/MVCGridHandler.axd/script.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/Common/AjaxForms.js")
    @RenderSection("scripts", required: false)
</body>
</html>

Announcements/Views/Shared/_Messages.cshtml
@using System.Collections
@using Announcements.Helpers.Classes
@model string
@{
    ArrayList messages = ((ArrayList)Session["pageMessages"]) ?? new ArrayList();
    var listMessages = messages.Cast<object>().ToList().Select(s=>new
    {
        message=s,
        order = s is string || s is ErrorMessage ? 1 : s is WarnMessage ? 2 : 3
    });
    Session["pageMessages"] = new ArrayList();
}

<div id="global-messages" class="global-messages @Model">
    @if (listMessages.Any(a => a.order == 1))
    {
        <div class="text-left alert alert-danger global-message-item">
            <button type="button" class="close" aria-label="Close" data-dismiss="alert">
                <span aria-hidden="true">x</span>
            </button>
            @foreach (var message in listMessages.Where(w=>w.order==1).OrderBy(o => o.order))
            {
                <p class="alert-text">@message.message</p>
            }
        </div>
    }
    @if (listMessages.Any(a => a.order == 2))
    {
        <div class="text-left alert alert-warning global-message-item">
            <button type="button" class="close" aria-label="Close" data-dismiss="alert">
                <span aria-hidden="true">x</span>
            </button>
            @foreach (var message in listMessages.Where(w => w.order == 2).OrderBy(o => o.order))
            {
                <p class="alert-text">@message.message</p>
            }
        </div>
    }    
    @if (listMessages.Any(a => a.order == 3))
    {
        <div class="text-left alert alert-success global-message-item">
            <button type="button" class="close" aria-label="Close" data-dismiss="alert">
                <span aria-hidden="true">x</span>
            </button>
            @foreach (var message in listMessages.Where(w => w.order == 3).OrderBy(o => o.order))
            {
                <p class="alert-text">@message.message</p>
            }
        </div>
    }
</div>
@if (listMessages.Any())
{
    <script>
        setTimeout(function(){$("#global-messages").html("")},2000);
    </script>
}